import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Sidebar & Navigation
    dashboard: 'Dashboard',
    file_complaint: 'File Complaint',
    report_breakdown: 'Report Breakdown',
    overview: 'Overview',
    complaints: 'Complaints',
    driver_performance: 'Driver Performance',
    user_management: 'User Management',
    bus_management: 'Bus Management',
    route_management: 'Route Management',
    logout: 'Logout',
    select_language: 'Select Language',
    welcome: 'Welcome to SafeRide+',
    
    // Auth & Landing
    get_started: 'Get Started',
    login_to_dashboard: 'Login to Dashboard',
    learn_more: 'Learn More',
    hero_title: 'Driver-Centric Smart Bus Management',
    hero_subtitle: 'Empowering college transportation with real-time feedback, performance monitoring, and enhanced student safety.',
    student_safety: 'Student Safety',
    student_safety_desc: 'Anonymous reporting system ensures students can voice concerns without hesitation.',
    driver_perf_desc: 'Dynamic scoring system incentivizes safe driving and professional behavior.',
    smart_analytics_title: 'Smart Analytics',
    smart_analytics_desc: 'In-depth reports on delays and overcrowding help optimize bus schedules.',
    copyright: 'All rights reserved.',
    role_selection_title: 'Who are you?',
    role_selection_subtitle: 'Select your role to access the SafeRide+ ecosystem.',
    student_desc: 'Report issues, view bus delays and overcrowding reports.',
    driver_desc: 'View bus info, track performance and report breakdowns.',
    in_charge_desc: 'Monitor complaints, analytics and driver performance.',
    admin_desc: 'Manage users, buses, routes and system configurations.',
    continue_as: 'Continue as {{role}}',
    back_to_home: '← Back to Home',
    change_role: 'Change Role',
    login_as: 'Login As',
    select_role_option: 'Select Role',
    welcome_back: 'Welcome Back',
    sign_in_to_continue: 'Sign in to SafeRide+ to continue',
    sign_in: 'Sign In',
    no_account: "Don't have an account?",
    contact_admin: 'Contact Administrator',
    invalid_credentials: 'Invalid email or password',
    profile_error: 'Unable to load your profile. Please check Firebase permissions.',
    login_title_role: '{{role}} Login',

    // Admin Dashboard
    system_admin: 'System Administration',
    manage_system: 'Manage users, vehicles, and network configurations.',
    users: 'Users',
    buses: 'Buses',
    routes: 'Routes',
    add_new: 'Add New',
    full_name: 'Full Name',
    email_address: 'Email Address',
    role: 'Role',
    assigned_bus: 'Assigned Bus (Drivers Only)',
    bus_number: 'Bus Number',
    capacity: 'Capacity',
    source: 'Source',
    destination: 'Destination',
    save: 'Save',
    saving: 'Saving...',
    quick_overview: 'Quick Overview',
    total_users: 'Total Users',
    active_buses: 'Active Buses',
    pending_complaints: 'Pending Complaints',
    recent_logs: 'Recent Logs',

    // Driver Dashboard
    driver_dashboard: 'Driver Dashboard',
    welcome_driver: 'Safe travels, {{name}}!',
    safety_points: 'Safety Points',
    arrival_log: 'Campus Arrival Log',
    arrival_log_desc: 'One-click recording for your arrival time at campus.',
    record_arrival: 'RECORD ARRIVAL NOW',
    bus_details: 'Bus Details',
    schedule: 'Schedule',
    next_shift: 'Next Shift',
    status: 'Status',
    on_duty: 'On Duty',
    action_center: 'Action Center',
    report_emergency: 'Report Emergency',
    safety_guidelines: 'Safety Guidelines',
    safety_guidelines_desc: 'Maintain constant speed and always yield to students at crossings.',
    emergency_breakdowns: 'Emergency & Breakdowns',
    emergency_desc: 'Quickly alert the network and find backup assistance.',
    location_landmark: 'Location / Landmark',
    breakdown_form_desc: 'Reporting a breakdown will automatically notify the Transport In-Charge and alert all backup drivers in the network.',
    report_emergency_breakdown: 'Report Emergency Breakdown',
    backup_assistance: 'Backup Assistance',
    backup_driver: 'Backup Driver',
    no_backup_drivers: 'No backup drivers currently registered.',
    breakdown_reported_success: 'Breakdown reported! Nearby buses and the Transport Head have been alerted.',
    breakdown_reported_error: 'Failed to report breakdown.',

    // Student Dashboard
    student_dashboard: 'Student Dashboard',
    ready_for_ride: 'Ready for your ride today?',
    live_bus_status: 'Live Bus Status',
    your_route: 'Your Route',
    on_schedule: 'On Schedule',
    upcoming_timings: 'Upcoming Bus Timings',
    announcements: 'Announcements',
    report_anonymous_issue: 'REPORT AN ANONYMOUS ISSUE',
    to: 'To',
    at: 'at',
    anonymous_complaint: 'Anonymous Complaint',
    anonymous_desc: 'Your identity will not be shared with the driver or transport staff.',
    report_issue: 'Report an Issue',
    issue_type: 'Issue Type',
    rash_behavior: 'Rash Driving / Behavior',
    bus_delay: 'Bus Delay',
    bus_hygiene: 'Bus Hygiene',
    other: 'Other',
    description_placeholder: 'Briefly describe what happened...',
    submit_anonymously: 'Submit Anonymously',
    complaint_submitted_success: 'Thank you! Your complaint has been submitted anonymously.',
    complaint_submitted_error: 'Failed to submit complaint. Please try again.',

    // In-Charge Dashboard
    transport_overview: 'Transport Systems Overview',
    live_monitor: 'Live health monitor of the SafeRide+ network.',
    manage_fleet: 'Manage Fleet',
    total_grievances: 'Total Grievances',
    system_delays: 'System Delays',
    active_alerts: 'Active Alerts',
    fleet_health: 'Fleet Health',
    system_insights: 'System Insights',
    delay_analysis: 'Delay Analysis',
    analyze_performance: 'Analyze Driver Performance',
    efficiency_trends: 'Efficiency Trends',
    complaints_management: 'Complaints Management',
    complaints_desc: 'Review and resolve issues reported by students securely.',
    no_complaints: 'No complaints found. Your transport network is running smooth!',
    mark_resolved: 'Mark Resolved',
    resolved: 'Resolved',
    pending: 'Pending',
    performance_analytics: 'Performance Analytics',
    performance_desc: 'Monitor driver safety scores and system efficiency.',
    delayed_arrivals: 'Delayed Arrivals',
    overcrowding_alerts: 'Overcrowding Alerts',
    avg_efficiency: 'Avg Efficiency',
    driver_safety_rankings: 'Driver Safety Rankings',
    driver_name: 'Driver Name',
    penalize: 'Penalize',
    penalize_reason_prompt: 'Reason for point deduction (e.g., Rash Driving):',
    points_deducted_success: '5 Points deducted successfully',
    failed_deduct_points: 'Failed to deduct points',
    failed_load_performance: 'Failed to load performance data',
    processing: 'Processing...',

    // Common/Misc
    student: 'Student',
    driver: 'Driver',
    transport_in_charge: 'Transport In-Charge',
    admin: 'Administrator',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error'
  },
  hi: {
    // Sidebar & Navigation
    dashboard: 'डैशबोर्ड',
    file_complaint: 'शिकायत दर्ज करें',
    report_breakdown: 'ब्रेकडाउन रिपोर्ट',
    overview: 'अवलोकन',
    complaints: 'शिकायतें',
    driver_performance: 'ड्राइवर प्रदर्शन',
    user_management: 'उपयोगकर्ता प्रबंधन',
    bus_management: 'बस प्रबंधन',
    route_management: 'मार्ग प्रबंधन',
    logout: 'लॉगआउट',
    select_language: 'भाषा चुनें',
    welcome: 'SafeRide+ में आपका स्वागत है',

    // Auth & Landing
    get_started: 'शुरू करें',
    login_to_dashboard: 'डैशबोर्ड में लॉग इन करें',
    learn_more: 'अधिक जानें',
    hero_title: 'ड्राइवर-केंद्रित स्मार्ट बस प्रबंधन',
    hero_subtitle: 'वास्तविक समय प्रतिक्रिया, प्रदर्शन निगरानी और बेहतर छात्र सुरक्षा के साथ कॉलेज परिवहन को सशक्त बनाना।',
    student_safety: 'छात्र सुरक्षा',
    student_safety_desc: 'अनाम रिपोर्टिंग प्रणाली सुनिश्चित करती है कि छात्र बिना किसी संकोच के अपनी चिंताएं व्यक्त कर सकें।',
    driver_perf_desc: 'गतिशील स्कोरिंग प्रणाली सुरक्षित ड्राइविंग और पेशेवर व्यवहार को प्रोत्साहित करती है।',
    smart_analytics_title: 'स्मार्ट एनालिटिक्स',
    smart_analytics_desc: 'देरी और भीड़भाड़ पर विस्तृत रिपोर्ट बस शेड्यूल को अनुकूलित करने में मदद करती है।',
    copyright: 'सर्वाधिकार सुरक्षित।',
    role_selection_title: 'आप कौन हैं?',
    role_selection_subtitle: 'SafeRide+ पारिस्थितिकी तंत्र तक पहुँचने के लिए अपनी भूमिका चुनें।',
    student_desc: 'समस्याओं की रिपोर्ट करें, बस की देरी और भीड़भाड़ की रिपोर्ट देखें।',
    driver_desc: 'बस की जानकारी देखें, प्रदर्शन को ट्रैक करें और ब्रेकडाउन की रिपोर्ट करें।',
    in_charge_desc: 'शिकायतों, एनालिटिक्स और ड्राइवर प्रदर्शन की निगरानी करें।',
    admin_desc: 'उपयोगकर्ताओं, बसों, मार्गों और सिस्टम कॉन्फ़िगरेशन को प्रबंधित करें।',
    continue_as: '{{role}} के रूप में जारी रखें',
    back_to_home: '← होम पर वापस जाएं',
    change_role: 'भूमिका बदलें',
    login_as: 'इस रूप में लॉग इन करें',
    select_role_option: 'भूमिका चुनें',
    welcome_back: 'वापसी पर स्वागत है',
    sign_in_to_continue: 'जारी रखने के लिए SafeRide+ में साइन इन करें',
    sign_in: 'साइन इन करें',
    no_account: "क्या आपका अकाउंट नहीं है?",
    contact_admin: 'प्रशासक से संपर्क करें',
    invalid_credentials: 'अमान्य ईमेल या पासवर्ड',
    profile_error: 'आपकी प्रोफ़ाइल लोड करने में असमर्थ। कृपया फ़ायरबेस अनुमतियों की जाँच करें।',
    login_title_role: '{{role}} लॉगिन',

    // Admin Dashboard
    system_admin: 'सिस्टम प्रशासन',
    manage_system: 'उपयोगकर्ताओं, वाहनों और नेटवर्क कॉन्फ़िगरेशन को प्रबंधित करें।',
    users: 'उपयोगकर्ता',
    buses: 'बसें',
    routes: 'मार्ग',
    add_new: 'नया जोड़ें',
    full_name: 'पूरा नाम',
    email_address: 'ईमेल पता',
    role: 'भूमिका',
    assigned_bus: 'निर्धारित बस (केवल ड्राइवर)',
    bus_number: 'बस नंबर',
    capacity: 'क्षमता',
    source: 'स्रोत',
    destination: 'गंतव्य',
    save: 'सहेजें',
    saving: 'सहेजा जा रहा है...',
    quick_overview: 'त्वरित अवलोकन',
    total_users: 'कुल उपयोगकर्ता',
    active_buses: 'सक्रिय बसें',
    pending_complaints: 'लंबित शिकायतें',
    recent_logs: 'हाल के लॉग',

    // Driver Dashboard
    driver_dashboard: 'ड्राइवर डैशबोर्ड',
    welcome_driver: 'सुरक्षित यात्रा, {{name}}!',
    safety_points: 'सुरक्षा अंक',
    arrival_log: 'कैंपस आगमन लॉग',
    arrival_log_desc: 'कैंपस में आपके आगमन के समय के लिए वन-क्लिक रिकॉर्डिंग।',
    record_arrival: 'अब आगमन रिकॉर्ड करें',
    bus_details: 'बस विवरण',
    schedule: 'अनुसूची',
    next_shift: 'अगली शिफ्ट',
    status: 'स्थिति',
    on_duty: 'ड्यूटी पर',
    action_center: 'एक्शन सेंटर',
    report_emergency: 'आपातकाल की रिपोर्ट करें',
    safety_guidelines: 'सुरक्षा दिशानिर्देश',
    safety_guidelines_desc: 'निरंतर गति बनाए रखें और हमेशा क्रॉसिंग पर छात्रों को रास्ता दें।',
    emergency_breakdowns: 'आपातकालीन और ब्रेकडाउन',
    emergency_desc: 'नेटवर्क को तुरंत सतर्क करें और बैकअप सहायता प्राप्त करें।',
    location_landmark: 'स्थान / लैंडमार्क',
    breakdown_form_desc: 'ब्रेकडाउन की रिपोर्ट करने से परिवहन प्रभारी को स्वचालित रूप से सूचित किया जाएगा और नेटवर्क में सभी बैकअप ड्राइवरों को सतर्क किया जाएगा।',
    report_emergency_breakdown: 'आपातकालीन ब्रेकडाउन की रिपोर्ट करें',
    backup_assistance: 'बैकअप सहायता',
    backup_driver: 'बैकअप ड्राइवर',
    no_backup_drivers: 'वर्तमान में कोई बैकअप ड्राइवर पंजीकृत नहीं है।',
    breakdown_reported_success: 'ब्रेकडाउन की सूचना दी गई! पास की बसों और परिवहन प्रमुख को सतर्क कर दिया गया है।',
    breakdown_reported_error: 'ब्रेकडाउन रिपोर्ट करने में विफल।',

    // Student Dashboard
    student_dashboard: 'छात्र डैशबोर्ड',
    ready_for_ride: 'क्या आप आज अपनी सवारी के लिए तैयार हैं?',
    live_bus_status: 'लाइव बस स्थिति',
    your_route: 'आपका मार्ग',
    on_schedule: 'समय पर',
    upcoming_timings: 'आगामी बस समय',
    announcements: 'घोषणाएं',
    report_anonymous_issue: 'अनाम समस्या की रिपोर्ट करें',
    to: 'को',
    at: 'पर',
    anonymous_complaint: 'अनाम शिकायत',
    anonymous_desc: 'आपकी पहचान ड्राइवर या परिवहन कर्मचारियों के साथ साझा नहीं की जाएगी।',
    report_issue: 'समस्या की रिपोर्ट करें',
    issue_type: 'समस्या का प्रकार',
    rash_behavior: 'तेज ड्राइविंग / व्यवहार',
    bus_delay: 'बस की देरी',
    bus_hygiene: 'बस की स्वच्छता',
    other: 'अन्य',
    description_placeholder: 'संक्षेप में बताएं कि क्या हुआ...',
    submit_anonymously: 'अनाम रूप से सबमिट करें',
    complaint_submitted_success: 'धन्यवाद! आपकी शिकायत अनाम रूप से सबमिट कर दी गई है।',
    complaint_submitted_error: 'शिकायत सबमिट करने में विफल। कृपया पुन: प्रयास करें।',

    // In-Charge Dashboard
    transport_overview: 'परिवहन प्रणाली अवलोकन',
    live_monitor: 'SafeRide+ नेटवर्क का लाइव स्वास्थ्य मॉनिटर।',
    manage_fleet: 'बेड़े का प्रबंधन करें',
    total_grievances: 'कुल शिकायतें',
    system_delays: 'सिस्टम की देरी',
    active_alerts: 'सक्रिय अलर्ट',
    fleet_health: 'बेड़े का स्वास्थ्य',
    system_insights: 'सिस्टम अंतर्दृष्टि',
    delay_analysis: 'देरी विश्लेषण',
    analyze_performance: 'ड्राइवर प्रदर्शन का विश्लेषण करें',
    efficiency_trends: 'दक्षता रुझान',
    complaints_management: 'शिकायत प्रबंधन',
    complaints_desc: 'छात्रों द्वारा रिपोर्ट की गई समस्याओं की सुरक्षित रूप से समीक्षा और समाधान करें।',
    no_complaints: 'कोई शिकायत नहीं मिली। आपका परिवहन नेटवर्क सुचारू रूप से चल रहा है!',
    mark_resolved: 'समाधान के रूप में चिह्नित करें',
    resolved: 'समाधान किया गया',
    pending: 'लंबित',
    performance_analytics: 'प्रदर्शन एनालिटिक्स',
    performance_desc: 'ड्राइवर सुरक्षा स्कोर और सिस्टम दक्षता की निगरानी करें।',
    delayed_arrivals: 'विलंबित आगमन',
    overcrowding_alerts: 'भीड़भाड़ अलर्ट',
    avg_efficiency: 'औसत दक्षता',
    driver_safety_rankings: 'ड्राइवर सुरक्षा रैंकिंग',
    driver_name: 'ड्राइवर का नाम',
    penalize: 'दंडित करें',
    penalize_reason_prompt: 'अंक कटौती का कारण (जैसे, तेज ड्राइविंग):',
    points_deducted_success: '5 अंक सफलतापूर्वक काटे गए',
    failed_deduct_points: 'अंक काटने में विफल',
    failed_load_performance: 'प्रदर्शन डेटा लोड करने में विफल',
    processing: 'प्रसंस्करण...',

    // Common/Misc
    student: 'छात्र',
    driver: 'ड्राइवर',
    transport_in_charge: 'परिवहन प्रभारी',
    admin: 'प्रशासक',
    loading: 'लोड हो रहा है...',
    success: 'सफलता',
    error: 'त्रुटि'
  },
  te: {
    // Sidebar & Navigation
    dashboard: 'డ్యాష్‌బోర్డ్',
    file_complaint: 'ఫిర్యాదు చేయండి',
    report_breakdown: 'బ్రేక్‌డౌన్ రిపోర్ట్',
    overview: 'అవలోకనం',
    complaints: 'ఫిర్యాదులు',
    driver_performance: 'డ్రైవర్ పనితీరు',
    user_management: 'వినియోగదారు నిర్వహణ',
    bus_management: 'బస్సు నిర్వహణ',
    route_management: 'రూట్ నిర్వహణ',
    logout: 'లాగ్ అవుట్',
    select_language: 'భాషను ఎంచుకోండి',
    welcome: 'SafeRide+ కి స్వాగతం',

    // Auth & Landing
    get_started: 'ప్రారంభించండి',
    login_to_dashboard: 'డ్యాష్‌బోర్డ్‌కి లాగిన్ అవ్వండి',
    learn_more: 'మరింత తెలుసుకోండి',
    hero_title: 'డ్రైవర్-సెంట్రిక్ స్మార్ట్ బస్ మేనేజ్‌మెంట్',
    hero_subtitle: 'రియల్-టైమ్ ఫీడ్‌బ్యాక్, పనితీరు పర్యవేక్షణ మరియు మెరుగైన విద్యార్థుల భద్రతతో కళాశాల రవాణాను బలోపేతం చేయడం.',
    student_safety: 'విద్యార్థుల భద్రత',
    student_safety_desc: 'అజ్ఞాత రిపోర్టింగ్ సిస్టమ్ విద్యార్థులు ఎటువంటి సంకోచం లేకుండా ఆందోళనలను తెలియజేయగలరని నిర్ధారిస్తుంది.',
    driver_perf_desc: 'డైనమిక్ స్కోరింగ్ సిస్టమ్ సురక్షిత డ్రైవింగ్ మరియు వృత్తిపరమైన ప్రవర్తనను ప్రోత్సహిస్తుంది.',
    smart_analytics_title: 'స్మార్ట్ అనలిటిక్స్',
    smart_analytics_desc: 'ఆలస్యం మరియు రద్దీపై లోతైన నివేదికలు బస్సు షెడ్యూల్‌లను ఆప్టిమైజ్ చేయడంలో సహాయపడతాయి.',
    copyright: 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    role_selection_title: 'మీరు ఎవరు?',
    role_selection_subtitle: 'SafeRide+ ఎకోసిస్టమ్‌ను యాక్సెస్ చేయడానికి మీ పాత్రను ఎంచుకోండి.',
    student_desc: 'సమస్యలను నివేదించండి, బస్సు ఆలస్యం మరియు రద్దీ నివేదికలను చూడండి.',
    driver_desc: 'బస్సు సమాచారాన్ని చూడండి, పనితీరును ట్రాక్ చేయండి మరియు బ్రేక్‌డౌన్‌లను నివేదించండి.',
    in_charge_desc: 'ఫిర్యాదులు, అనలిటిక్స్ మరియు డ్రైవర్ పనితీరును పర్యవేక్షించండి.',
    admin_desc: 'వినియోగదారులు, బస్సులు, మార్గాలు మరియు సిస్టమ్ కాన్ఫిగరేషన్‌లను నిర్వహించండి.',
    continue_as: '{{role}}గా కొనసాగండి',
    back_to_home: '← హోమ్‌కి తిరిగి వెళ్లు',
    change_role: 'పాత్రను మార్చండి',
    login_as: 'ఇలా లాగిన్ అవ్వండి',
    select_role_option: 'పాత్రను ఎంచుకోండి',
    welcome_back: 'తిరిగి స్వాగతం',
    sign_in_to_continue: 'కొనసాగించడానికి SafeRide+కి సైన్ ఇన్ చేయండి',
    sign_in: 'సైన్ ఇన్ చేయండి',
    no_account: "మీకు ఖాతా లేదా?",
    contact_admin: 'అడ్మినిస్ట్రేటర్‌ని సంప్రదించండి',
    invalid_credentials: 'చెల్లని ఈమెయిల్ లేదా పాస్‌వర్డ్',
    profile_error: 'మీ ప్రొఫైల్‌ను లోడ్ చేయడం సాధ్యం కాలేదు. దయచేసి ఫైర్‌బేస్ అనుమతులను తనిఖీ చేయండి.',
    login_title_role: '{{role}} లాగిన్',

    // Admin Dashboard
    system_admin: 'సిస్టమ్ పరిపాలన',
    manage_system: 'వినియోగదారులు, వాహనాలు మరియు నెట్‌వర్క్ కాన్ఫిగరేషన్‌లను నిర్వహించండి.',
    users: 'వినియోగదారులు',
    buses: 'బస్సులు',
    routes: 'మార్గాలు',
    add_new: 'కొత్తది జోడించు',
    full_name: 'పూర్తి పేరు',
    email_address: 'ఈమెయిల్ చిరునామా',
    role: 'పాత్ర',
    assigned_bus: 'కేటాయించిన బస్సు (డ్రైవర్లు మాత్రమే)',
    bus_number: 'బస్సు సంఖ్య',
    capacity: 'సామర్థ్యం',
    source: 'మూలం',
    destination: 'గమ్యం',
    save: 'సేవ్ చేయి',
    saving: 'సేవ్ అవుతోంది...',
    quick_overview: 'త్వరిత అవలోకనం',
    total_users: 'మొత్తం వినియోగదారులు',
    active_buses: 'క్రియాశీల బస్సులు',
    pending_complaints: 'పెండింగ్‌లో ఉన్న ఫిర్యాదులు',
    recent_logs: 'ఇటీవలి లాగ్‌లు',

    // Driver Dashboard
    driver_dashboard: 'డ్రైవర్ డ్యాష్‌బోర్డ్',
    welcome_driver: 'సురక్షిత ప్రయాణం, {{name}}!',
    safety_points: 'భద్రతా పాయింట్లు',
    arrival_log: 'క్యాంపస్ రాక లాగ్',
    arrival_log_desc: 'క్యాంపస్‌కు మీరు చేరుకున్న సమయం కోసం వన్-క్లిక్ రికార్డింగ్.',
    record_arrival: 'ఇప్పుడే రాకను రికార్డ్ చేయండి',
    bus_details: 'బస్సు వివరాలు',
    schedule: 'షెడ్యూల్',
    next_shift: 'తదుపరి షిఫ్ట్',
    status: 'స్థితి',
    on_duty: 'డ్యూటీలో ఉన్నారు',
    action_center: 'యాక్షన్ సెంటర్',
    report_emergency: 'అత్యవసర పరిస్థితిని నివేదించండి',
    safety_guidelines: 'భద్రతా మార్గదర్శకాలు',
    safety_guidelines_desc: 'స్థిరమైన వేగాన్ని నిర్వహించండి మరియు క్రాసింగ్‌ల వద్ద విద్యార్థులకు ఎల్లప్పుడూ దారి ఇవ్వండి.',
    emergency_breakdowns: 'అత్యవసర మరియు బ్రేక్‌డౌన్‌లు',
    emergency_desc: 'నెట్‌వర్క్‌ను త్వరగా అప్రమత్తం చేయండి మరియు బ్యాకప్ సహాయాన్ని కనుగొనండి.',
    location_landmark: 'స్థలం / ల్యాండ్‌మార్క్',
    breakdown_form_desc: 'బ్రేక్‌డౌన్‌ను నివేదించడం ద్వారా రవాణా ఇన్-చార్జ్‌కి స్వయంచాలక సమాచారం వెళ్తుంది మరియు నెట్‌వర్క్‌లోని బ్యాకప్ డ్రైవర్లందరినీ అప్రమత్తం చేస్తుంది.',
    report_emergency_breakdown: 'అత్యవసర బ్రేక్‌డౌన్‌ను నివేదించండి',
    backup_assistance: 'బ్యాకప్ సహాయం',
    backup_driver: 'బ్యాకప్ డ్రైవర్',
    no_backup_drivers: 'ప్రస్తుతం బ్యాకప్ డ్రైవర్లు ఎవరూ నమోదు కాలేదు.',
    breakdown_reported_success: 'బ్రేక్‌డౌన్ నివేదించబడింది! సమీపంలోని బస్సులు మరియు రవాణా అధిపతి అప్రమత్తం చేయబడ్డారు.',
    breakdown_reported_error: 'బ్రేక్‌డౌన్‌ను నివేదించడంలో విఫలమైంది.',

    // Student Dashboard
    student_dashboard: 'విద్యార్థి డ్యాష్‌బోర్డ్',
    ready_for_ride: 'ఈరోజు మీ ప్రయాణానికి సిద్ధంగా ఉన్నారా?',
    live_bus_status: 'లైవ్ బస్సు స్థితి',
    your_route: 'మీ రూట్',
    on_schedule: 'షెడ్యూల్ ప్రకారం',
    upcoming_timings: 'రాబోయే బస్సు సమయాలు',
    announcements: 'ప్రకటనలు',
    report_anonymous_issue: 'అజ్ఞాత సమస్యను నివేదించండి',
    to: 'కి',
    at: 'వద్ద',
    anonymous_complaint: 'అజ్ఞాత ఫిర్యాదు',
    anonymous_desc: 'మీ గుర్తింపు డ్రైవర్ లేదా రవాణా సిబ్బందితో పంచుకోబడదు.',
    report_issue: 'సమస్యను నివేదించండి',
    issue_type: 'సమస్య రకం',
    rash_behavior: 'వేగవంతమైన డ్రైవింగ్ / ప్రవర్తన',
    bus_delay: 'బస్సు ఆలస్యం',
    bus_hygiene: 'బస్సు పరిశుభ్రత',
    other: 'ఇతర',
    description_placeholder: 'ఏమి జరిగిందో సంక్షిప్తంగా వివరించండి...',
    submit_anonymously: 'అజ్ఞాతంగా సమర్పించండి',
    complaint_submitted_success: 'ధన్యవాదాలు! మీ ఫిర్యాదు అజ్ఞాతంగా సమర్పించబడింది.',
    complaint_submitted_error: 'ఫిర్యాదును సమర్పించడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',

    // In-Charge Dashboard
    transport_overview: 'రవాణా వ్యవస్థల అవలోకనం',
    live_monitor: 'SafeRide+ నెట్‌వర్క్ యొక్క లైవ్ హెల్త్ మానిటర్.',
    manage_fleet: 'ఫ్లీట్‌ను నిర్వహించండి',
    total_grievances: 'మొత్తం ఫిర్యాదులు',
    system_delays: 'సిస్టమ్ ఆలస్యం',
    active_alerts: 'క్రియాశీల హెచ్చరికలు',
    fleet_health: 'ఫ్లీట్ ఆరోగ్యం',
    system_insights: 'సిస్టమ్ అంతర్దృష్టులు',
    delay_analysis: 'ఆలస్యం విశ్లేషణ',
    analyze_performance: 'డ్రైవర్ పనితీరును విశ్లేషించండి',
    efficiency_trends: 'సామర్థ్య పోకడలు',
    complaints_management: 'ఫిర్యాదుల నిర్వహణ',
    complaints_desc: 'విద్యార్థులు నివేదించిన సమస్యలను సురక్షితంగా సమీక్షించండి మరియు పరిష్కరించండి.',
    no_complaints: 'ఫిర్యాదులు ఏవీ లేవు. మీ రవాణా నెట్‌వర్క్ సాఫీగా నడుస్తోంది!',
    mark_resolved: 'పరిష్కరించబడినట్లు గుర్తు గుర్తించండి',
    resolved: 'పరిష్కరించబడింది',
    pending: 'పెండింగ్‌లో ఉంది',
    performance_analytics: 'పనితీరు విశ్లేషణ',
    performance_desc: 'డ్రైవర్ భద్రత స్కోర్‌లు మరియు సిస్టమ్ సామర్థ్యాన్ని పర్యవేక్షించండి.',
    delayed_arrivals: 'ఆలస్యంగా రాక',
    overcrowding_alerts: 'రద్దీ హెచ్చరికలు',
    avg_efficiency: 'సగటు సామర్థ్యం',
    driver_safety_rankings: 'డ్రైవర్ భద్రతా ర్యాంకింగ్‌లు',
    driver_name: 'డ్రైవర్ పేరు',
    penalize: 'శిక్షించండి',
    penalize_reason_prompt: 'పాయింట్ల తగ్గింపుకు కారణం (ఉదా., వేగవంతమైన డ్రైవింగ్):',
    points_deducted_success: '5 పాయింట్లు విజయవంతంగా తగ్గించబడ్డాయి',
    failed_deduct_points: 'పాయింట్లను తగ్గించడంలో విఫలమైంది',
    failed_load_performance: 'పనితీరు డేటాను లోడ్ చేయడంలో విఫలమైంది',
    processing: 'ప్రాసెస్ అవుతోంది...',

    // Common/Misc
    student: 'విద్యార్థి',
    driver: 'డ్రైవర్',
    transport_in_charge: 'రవాణా ఇన్-చార్జ్',
    admin: 'అడ్మినిస్ట్రేటర్',
    loading: 'లోడ్ అవుతోంది...',
    success: 'విజయం',
    error: 'లోపం'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key, params = {}) => {
    let text = translations[language][key] || key;
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{{${k}}}`, v);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
